### ISSUE TITLE
免驱独显掉帧问题

### ISSUE THREAD

**Issue by AlphaGHX** [anlostsheep/hackintosh-colorful-b460i#5]
hi 大佬，我其他硬件基本和你相同除了我是 RX580，同时我是用的自己的 EFI。
我有一个问题：显卡跑分 or 玩游戏（高负载情况下）性能表现正常，独显得到了合理的调用。但是在日常使用，比如浏览网页，鼠标滚动界面时会出现掉帧问题。
开机使用一段时间后大概率可以通用 [testufo](https://testufo.com/) 复现：表现为肉眼可见的掉帧。不知道你是否遇到过这种问题？其实我已经在网上找了一圈但是没找到合适的解法。

**Comment by pokipoi** [comment]
几个建议的方法，显卡方面的问题的话有几个排除思路，因为导致问题的因素有很多。
1尝试不同版本的whatevergreen.kext
2尝试不同版本的显卡bios
3给显卡bios刷哥gop uefi
4显卡排除法，用集成显卡或者其它显卡排除问题所在
5系统排除法，安装不同版本的系统进行排除
总之很耗精力，看你操作

**Comment by AlphaGHX** [comment]
总之真的折腾不动了，老老实实用 windows 了，还是谢谢大佬啦
