### ISSUE TITLE
您好，是否可以出一版不含独立显卡的EFI。

### ISSUE THREAD

**Issue by nashzosi** [anlostsheep/hackintosh-colorful-b460i#6]
> 感谢您分享的EFI文件，我使用它的时候碰到了一些问题，看看您是否有时间给指导一二 您好我的硬件配置如下，硬件配置 CPU | Intel i5-10600 主板 | 七彩虹 B460I CVN Forzen V20 内存 | 万紫千红8G x2 硬盘 | 三星sn550 1T 显卡 | 无 网卡 | 博通 BCM94360CS2 机箱 | 超频三蜂鸟1
> 
> 使用您的EFI安装macOS Ventura 13.x无法进入安装界面报错如下 ![0c081e7ac8773d46f835746c9cf1f7f](https://user-images.githubusercontent.com/40159695/255844344-c53578ef-59e0-41d5-abc9-99da9927af55.jpg) 然后我使用了其他人的EFI成功安装并且成功进入系统https://github.com/AlphaGHX/Hackintosh-CVN-b460i-efi

然后再使用您的efi启动无法进入系统报错如下，每次启动都不一样：
![6e4775a1af577185f176e5634c15744](https://github.com/anlostsheep/hackintosh-colorful-b460i/assets/40159695/751c397c-07ad-4d25-832d-cb653a73326b)
![b32ceb82ae082a035665aa41317f7e7](https://github.com/anlostsheep/hackintosh-colorful-b460i/assets/40159695/333cc93f-d195-4e98-ac79-3b5f5ee9e6b3)
![5a07299b4b9d0d18b1825638f3e3ef3](https://github.com/anlostsheep/hackintosh-colorful-b460i/assets/40159695/c9834a1c-5b8d-43b0-a4b9-728a53ed6291)
由于没有报错 不知道应该从哪个方向努力
最终怀疑是没有独立显卡的原因，希望您可以出一个不含独立显卡的efi文件

**Comment by FengWeichang** [comment]
> 感谢您分享的EFI文件，我使用它的时候碰到了一些问题，看看您是否有时间给指导一二 您好我的硬件配置如下，硬件配置 CPU | Intel i5-10600 主板 | 七彩虹 B460I CVN Forzen V20 内存 | 万紫千红8G x2 硬盘 | 三星sn550 1T 显卡 | 无 网卡 | 博通 BCM94360CS2 机箱 | 超频三蜂鸟1
> 
> 使用您的EFI安装macOS Ventura 13.x无法进入安装界面报错如下 ![0c081e7ac8773d46f835746c9cf1f7f](https://user-images.githubusercontent.com/40159695/255844344-c53578ef-59e0-41d5-abc9-99da9927af55.jpg) 然后我使用了其他人的EFI成功安装并且成功进入系统https://github.com/AlphaGHX/Hackintosh-CVN-b460i-efi

然后再使用您的efi启动无法进入系统报错如下，每次启动都不一样：
![6e4775a1af577185f176e5634c15744](https://github.com/anlostsheep/hackintosh-colorful-b460i/assets/40159695/751c397c-07ad-4d25-832d-cb653a73326b)
![b32ceb82ae082a035665aa41317f7e7](https://github.com/anlostsheep/hackintosh-colorful-b460i/assets/40159695/333cc93f-d195-4e98-ac79-3b5f5ee9e6b3)
![5a07299b4b9d0d18b1825638f3e3ef3](https://github.com/anlostsheep/hackintosh-colorful-b460i/assets/40159695/c9834a1c-5b8d-43b0-a4b9-728a53ed6291)
由于没有报错 不知道应该从哪个方向努力
最终怀疑是没有独立显卡的原因，希望您可以出一个不含独立显卡的efi文件

**Comment by anlostsheep** [comment]
1. 修改 /EFI/OC/config.plist 中的 `DeviceProperties` 的 `AAPL,ig-platform-id` 属性为以下
![image](https://github.com/anlostsheep/hackintosh-colorful-b460i/assets/45201628/97b564b8-f0e9-40e5-9892-53b43514fa19)
</br>

2. 启动界面选择磁盘引导时执行 Clean NVRAM 清理并重新启动

**Comment by nashzosi** [comment]
非常感谢！
